In [1]:
#Import the lirbaries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [17]:
#Loading the Iris Dataset from Seaborn to work on logistic Regression

data=sns.load_dataset('iris')

In [18]:
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

### For any machine algorithm to build the first very importatant thing to keep in mind is
#### 1 Data should be complete
#### 2 Data should be numeric

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [20]:
data.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

#### No null values are present

## Here all independent features are numeric hence no conversion required but here we see that the dependant feature i.e. Label Species is categorical
## we need to convert this to numeric

In [21]:
#First lets check how many unique values are present in the label
data['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [22]:
# Here we are having 3 class, as of now we will work only with the binary class classification so we will drop on of the values i.e. setosa
data=data[data['species']!='setosa']

In [23]:
data

sepal_length  sepal_width  petal_length  petal_width     species
50            7.0          3.2           4.7          1.4  versicolor
51            6.4          3.2           4.5          1.5  versicolor
52            6.9          3.1           4.9          1.5  versicolor
53            5.5          2.3           4.0          1.3  versicolor
54            6.5          2.8           4.6          1.5  versicolor
..            ...          ...           ...          ...         ...
145           6.7          3.0           5.2          2.3   virginica
146           6.3          2.5           5.0          1.9   virginica
147           6.5          3.0           5.2          2.0   virginica
148           6.2          3.4           5.4          2.3   virginica
149           5.9          3.0           5.1          1.8   virginica

[100 rows x 5 columns]

In [32]:
data['species'].value_counts()

species
versicolor    50
virginica     50
Name: count, dtype: int64

### Also we see that this is balanced dataset

In [35]:
# Lets convert the species categorical to numerical, there are mulitple ways to do the same
data['species']=data['species'].map({'versicolor':0, 'virginica':1})

In [36]:
data.head()

sepal_length  sepal_width  petal_length  petal_width  species
50           7.0          3.2           4.7          1.4        0
51           6.4          3.2           4.5          1.5        0
52           6.9          3.1           4.9          1.5        0
53           5.5          2.3           4.0          1.3        0
54           6.5          2.8           4.6          1.5        0

In [37]:
data['species'].value_counts()

species
0    50
1    50
Name: count, dtype: int64

In [38]:
# Lets divide into features and labels to use into model

features=data.iloc[:,:4].values
label=data.iloc[:,-1].values

In [39]:
features

array([[7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3

In [40]:
label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [48]:
#Lets divide the data into train and test split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(features,
                                                 label,
                                                 test_size=0.25,
                                                 random_state=10)

In [49]:
X_train.shape

(75, 4)

In [50]:
y_train.shape

(75,)

In [51]:
X_test.shape

(25, 4)

In [52]:
y_test.shape

(25,)

### Lets build the base model to check to see if getting the generalized model

In [53]:
from sklearn.linear_model import LogisticRegression
logisticRegression1=LogisticRegression()

In [54]:
logisticRegression1.fit(X_train, y_train)

LogisticRegression()

In [59]:
model1_predict=logisticRegression1.predict(X_test)

In [56]:
trainScore1=logisticRegression1.score(X_train, y_train)
testScore1=logisticRegression1.score(X_test, y_test)

In [57]:
print(f"Test Score: {testScore1} and Train Score: {trainScore1}")

Test Score: 1.0 and Train Score: 0.96


#### We see that the selected RS itself giving a generalized model

In [63]:
#Lets check other metrics of the classification
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [60]:
score=accuracy_score(model1_predict, y_test)
print(score)

1.0


In [62]:
print(classification_report(model1_predict, y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00        13

    accuracy                           1.00        25
   macro avg       1.00      1.00      1.00        25
weighted avg       1.00      1.00      1.00        25



In [67]:
confusion_matrix(model1_predict, y_test)

array([[12,  0],
       [ 0, 13]], dtype=int64)

In [69]:
confusion_matrix(label, logisticRegression1.predict(features))

array([[48,  2],
       [ 1, 49]], dtype=int64)

### This concludes that the model does produce the generalized model however we can check to see if it is overfitting model as and when we progress